version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      TZ: Europe/Warsaw
    volumes:
      - ./db_data/:/data/db/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  minio:
    platform: linux/arm64
    image: bitnami/minio:latest
    container_name: "minio-s3"
    restart: unless-stopped
    tty: true
    environment:
      - "MINIO_ROOT_USER=root"
      - "MINIO_ROOT_PASSWORD=password"
      - "MINIO_DEFAULT_BUCKETS=img-cache:none,84ccbbab-e7ca-46f9-ae3e-d8f1e3939660:none,"
      - "MINIO_BROWSER=on"
      - "CONSOLE_SECURE_TLS_REDIRECT=off"
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_volume:/data
    networks:
      - network1

networks:
  network1:
    driver: bridge
volumes:
  minio_volume:
    driver: local
